title: "Along 83"
description: "Off-record observations and writings from a non-working cinematographer."
url: "https://kalin-s.github.io"
baseurl: "along83"

language: "en"

# Plugins supported by GitHub Pages
plugins:
  - jekyll-feed
  - jekyll-seo-tag

markdown: kramdown
highlighter: rouge

# Essays collection
collections:
  essays:
    output: true
    permalink: /theoreticallyhireable/:collection/:title/

# Include assets folder
include:
  - assets

# Default layout for essays
defaults:
  - scope:
      path: ""
      type: "essays"
    values:
      layout: default
